### ISSUE TITLE
もとからある変数名のうち一部が翻訳できない

### ISSUE THREAD

**Issue by sgk** [switch-education/pxt-microbit#2]
これの「list」とか。
![image](https://user-images.githubusercontent.com/485416/47665936-b5451f80-dbe5-11e8-90ec-68a8b65f0739.png)

**Comment by asondemita** [comment]
これの「recivedNumber」「name」「value」「receivedString」とか。
![radio](https://user-images.githubusercontent.com/7057616/47676547-41fcd700-dc00-11e8-890c-c17eebf26da5.png)

**Comment by asondemita** [comment]
> これの「recivedNumber」「name」「value」「receivedString」とか。
> ![radio](https://user-images.githubusercontent.com/7057616/47676547-41fcd700-dc00-11e8-890c-c17eebf26da5.png)



> これの「recivedNumber」「name」「value」「receivedString」とか。
> ![radio](https://user-images.githubusercontent.com/7057616/47676547-41fcd700-dc00-11e8-890c-c17eebf26da5.png)

https://github.com/switch-education/pxt-microbit/issues/6 として別にしました

**Comment by sgk** [comment]
配列のブロック群は翻訳できた。
スプライトのブロック群は翻訳できた。

**Comment by sgk** [comment]
![image](https://user-images.githubusercontent.com/485416/53609703-824e7f00-3c0b-11e9-8106-4bb315068a26.png)
![image](https://user-images.githubusercontent.com/485416/53609758-b32eb400-3c0b-11e9-8b7e-ec6650dc3bcd.png)

のこりはこれら。
